import { defineType, defineField, defineArrayMember } from 'sanity'

/**
 * Centralized Page Schema
 * 
 * ONE document per page with:
 * - Shared fields (slug, published status) - fill ONCE
 * - Localized fields (title, content, SEO) - translate
 */
export const pageCentralizedType = defineType({
  name: 'pageCentralized',
  title: 'Page',
  type: 'document',
  groups: [
    { name: 'general', title: '🌐 General', default: true },
    { name: 'homeHero', title: '🚀 Home: Hero' },
    { name: 'homeTrust', title: '🛡️ Home: Trust Strip' },
    { name: 'homeWhy', title: '🤔 Home: Why Choose Us' },
    { name: 'homeTestimonials', title: '💬 Home: Testimonials' },
    { name: 'homeCTA', title: '📢 Home: CTA' },
    { name: 'aboutContent', title: 'ℹ️ About: Content' },
    { name: 'content', title: '📝 Content', hidden: true }, // Hidden - not used on website
    { name: 'seo', title: '🔍 SEO' },
    { name: 'settings', title: '⚙️ Settings' },
  ],
  fields: [
    // ============================================
    // SETTINGS
    // ============================================
    defineField({
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      group: 'settings',
      options: {
        source: 'titleEn',
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'pageType',
      title: 'Page Type',
      type: 'string',
      group: 'settings',
      options: {
        list: [
          { title: '🏠 Home', value: 'home' },
          { title: 'ℹ️ About', value: 'about' },
          { title: '📞 Contact', value: 'contact' },
          { title: '📋 Services', value: 'services' },
          { title: '📄 Generic', value: 'generic' },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'isPublished',
      title: 'Published',
      type: 'boolean',
      group: 'settings',
      initialValue: true,
    }),
    defineField({
      name: 'order',
      title: 'Menu Order',
      type: 'number',
      group: 'settings',
      initialValue: 0,
    }),

    // ============================================
    // TITLES (Common)
    // ============================================
    defineField({
      name: 'titleAr',
      title: 'Title (Arabic)',
      type: 'string',
      group: 'general',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'titleEn',
      title: 'Title (English)',
      type: 'string',
      group: 'general',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'titleRu',
      title: 'Title (Russian)',
      type: 'string',
      group: 'general',
    }),

    // ============================================
    // HOME: HERO SECTION
    // ============================================
    defineField({
      name: 'heroTitleAr',
      title: 'Hero Title (Arabic)',
      type: 'string',
      group: 'homeHero',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'heroTitleEn',
      title: 'Hero Title (English)',
      type: 'string',
      group: 'homeHero',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'heroSubtitleAr',
      title: 'Hero Subtitle (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeHero',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'heroSubtitleEn',
      title: 'Hero Subtitle (English)',
      type: 'text',
      rows: 2,
      group: 'homeHero',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'heroVideo',
      title: 'Hero Video File (URL)',
      type: 'string',
      description: 'URL to the background video (e.g., /hero-video.MOV)',
      group: 'homeHero',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),

    // ============================================
    // HOME: TRUST STRIP
    // ============================================
    defineField({
      name: 'yearsExportingAr',
      title: 'Years (Arabic) [e.g. ١٥+ سنة]',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'yearsExportingEn',
      title: 'Years (English) [e.g. 15+ Years]',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'countriesServedAr',
      title: 'Countries (Arabic)',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'countriesServedEn',
      title: 'Countries (English)',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'certifiedAr',
      title: 'Certified Text (Arabic)',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'certifiedEn',
      title: 'Certified Text (English)',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'containersPerYearAr',
      title: 'Containers Text (Arabic)',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'containersPerYearEn',
      title: 'Containers Text (English)',
      type: 'string',
      group: 'homeTrust',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),

    // ============================================
    // HOME: PRODUCTS INTRO
    // ============================================
    defineField({
      name: 'ourPremiumProductsAr',
      title: 'Products Title (Arabic)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'ourPremiumProductsEn',
      title: 'Products Title (English)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'freshCertifiedDeliveredAr',
      title: 'Products Tagline (Arabic)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'freshCertifiedDeliveredEn',
      title: 'Products Tagline (English)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),

    // ============================================
    // HOME: WHY CHOOSE US
    // ============================================
    defineField({
      name: 'whyChooseUsAr',
      title: 'Why Choose Us Title (Arabic)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'whyChooseUsEn',
      title: 'Why Choose Us Title (English)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    // Individual Card 1
    defineField({
      name: 'qualityCertifiedAr',
      title: 'Quality Card Title (Arabic)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'qualityCertifiedEn',
      title: 'Quality Card Title (English)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'qualityCertifiedDescAr',
      title: 'Quality Card Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'qualityCertifiedDescEn',
      title: 'Quality Card Desc (English)',
      type: 'text',
      rows: 2,
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    // Individual Card 2
    defineField({
      name: 'reliableDeliveryAr',
      title: 'Delivery Card Title (Arabic)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'reliableDeliveryEn',
      title: 'Delivery Card Title (English)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'reliableDeliveryDescAr',
      title: 'Delivery Card Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'reliableDeliveryDescEn',
      title: 'Delivery Card Desc (English)',
      type: 'text',
      rows: 2,
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    // Individual Card 3
    defineField({
      name: 'freshGuaranteeAr',
      title: 'Guarantee Card Title (Arabic)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'freshGuaranteeEn',
      title: 'Guarantee Card Title (English)',
      type: 'string',
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'freshGuaranteeDescAr',
      title: 'Guarantee Card Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'freshGuaranteeDescEn',
      title: 'Guarantee Card Desc (English)',
      type: 'text',
      rows: 2,
      group: 'homeWhy',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),

    // ============================================
    // HOME: TESTIMONIALS (Raw for speed, maps to testimonialXQuote)
    // ============================================
    defineField({
      name: 'testimonial1QuoteAr',
      title: 'Testimonial 1 Quote (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial1QuoteEn',
      title: 'Testimonial 1 Quote (English)',
      type: 'text',
      rows: 2,
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial1AuthorAr',
      title: 'Testimonial 1 Author (Arabic)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial1AuthorEn',
      title: 'Testimonial 1 Author (English)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial1Company',
      title: 'Testimonial 1 Company',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial1Country',
      title: 'Testimonial 1 Country',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    // Testimonial 2
    defineField({
      name: 'testimonial2QuoteAr',
      title: 'Testimonial 2 Quote (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial2QuoteEn',
      title: 'Testimonial 2 Quote (English)',
      type: 'text',
      rows: 2,
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial2AuthorAr',
      title: 'Testimonial 2 Author (Arabic)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial2AuthorEn',
      title: 'Testimonial 2 Author (English)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial2Company',
      title: 'Testimonial 2 Company',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial2Country',
      title: 'Testimonial 2 Country',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    // Testimonial 3
    defineField({
      name: 'testimonial3QuoteAr',
      title: 'Testimonial 3 Quote (Arabic)',
      type: 'text',
      rows: 2,
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial3QuoteEn',
      title: 'Testimonial 3 Quote (English)',
      type: 'text',
      rows: 2,
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial3AuthorAr',
      title: 'Testimonial 3 Author (Arabic)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial3AuthorEn',
      title: 'Testimonial 3 Author (English)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial3Company',
      title: 'Testimonial 3 Company',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'testimonial3Country',
      title: 'Testimonial 3 Country',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    // Section Title
    defineField({
      name: 'whatClientsSayAr',
      title: 'Testimonials Section Title (Arabic)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'whatClientsSayEn',
      title: 'Testimonials Section Title (English)',
      type: 'string',
      group: 'homeTestimonials',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),

    // ============================================
    // HOME: CTA SECTION
    // ============================================
    defineField({
      name: 'readyToImportAr',
      title: 'CTA Title (Arabic)',
      type: 'string',
      group: 'homeCTA',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'readyToImportEn',
      title: 'CTA Title (English)',
      type: 'string',
      group: 'homeCTA',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'getCustomizedQuoteAr',
      title: 'CTA Subtitle (Arabic)',
      type: 'string',
      group: 'homeCTA',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'getCustomizedQuoteEn',
      title: 'CTA Subtitle (English)',
      type: 'string',
      group: 'homeCTA',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'getYourQuoteTodayAr',
      title: 'CTA Button Text (Arabic)',
      type: 'string',
      group: 'homeCTA',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'getYourQuoteTodayEn',
      title: 'CTA Button Text (English)',
      type: 'string',
      group: 'homeCTA',
      hidden: ({ document }) => document?.pageType !== 'home',
    }),


    // ============================================
    // ABOUT PAGE SPECIFIC
    // ============================================
    // Hero Section
    defineField({
      name: 'aboutAlSoadaaAr',
      title: 'About Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'aboutAlSoadaaEn',
      title: 'About Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'aboutAlSoadaaRu',
      title: 'About Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'aboutHeroSubtitleAr',
      title: 'Hero Subtitle (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'aboutHeroSubtitleEn',
      title: 'Hero Subtitle (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'aboutHeroSubtitleRu',
      title: 'Hero Subtitle (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    // Stats Section
    defineField({
      name: 'yearsOfExcellenceAr',
      title: 'Years of Excellence Label (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'yearsOfExcellenceEn',
      title: 'Years of Excellence Label (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'yearsOfExcellenceRu',
      title: 'Years of Excellence Label (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'containersAnnuallyAr',
      title: 'Containers Annually Label (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'containersAnnuallyEn',
      title: 'Containers Annually Label (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'containersAnnuallyRu',
      title: 'Containers Annually Label (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'customerSatisfactionAr',
      title: 'Customer Satisfaction Label (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'customerSatisfactionEn',
      title: 'Customer Satisfaction Label (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'customerSatisfactionRu',
      title: 'Customer Satisfaction Label (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    // Mission & Values Section
    defineField({
      name: 'ourMissionAndValuesAr',
      title: 'Mission & Values Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'ourMissionAndValuesEn',
      title: 'Mission & Values Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'ourMissionAndValuesRu',
      title: 'Mission & Values Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    // Value Cards
    defineField({
      name: 'qualityFirstAr',
      title: 'Quality First Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'qualityFirstEn',
      title: 'Quality First Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'qualityFirstRu',
      title: 'Quality First Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'qualityFirstDescAr',
      title: 'Quality First Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'qualityFirstDescEn',
      title: 'Quality First Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'qualityFirstDescRu',
      title: 'Quality First Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalReachAr',
      title: 'Global Reach Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalReachEn',
      title: 'Global Reach Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalReachRu',
      title: 'Global Reach Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalReachDescAr',
      title: 'Global Reach Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalReachDescEn',
      title: 'Global Reach Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalReachDescRu',
      title: 'Global Reach Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'sustainabilityAr',
      title: 'Sustainability Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'sustainabilityEn',
      title: 'Sustainability Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'sustainabilityRu',
      title: 'Sustainability Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'sustainabilityDescAr',
      title: 'Sustainability Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'sustainabilityDescEn',
      title: 'Sustainability Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'sustainabilityDescRu',
      title: 'Sustainability Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'partnershipAr',
      title: 'Partnership Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'partnershipEn',
      title: 'Partnership Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'partnershipRu',
      title: 'Partnership Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'partnershipDescAr',
      title: 'Partnership Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'partnershipDescEn',
      title: 'Partnership Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'partnershipDescRu',
      title: 'Partnership Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'innovationAr',
      title: 'Innovation Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'innovationEn',
      title: 'Innovation Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'innovationRu',
      title: 'Innovation Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'innovationDescAr',
      title: 'Innovation Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'innovationDescEn',
      title: 'Innovation Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'innovationDescRu',
      title: 'Innovation Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'trustAndReliabilityAr',
      title: 'Trust & Reliability Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'trustAndReliabilityEn',
      title: 'Trust & Reliability Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'trustAndReliabilityRu',
      title: 'Trust & Reliability Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'trustAndReliabilityDescAr',
      title: 'Trust & Reliability Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'trustAndReliabilityDescEn',
      title: 'Trust & Reliability Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'trustAndReliabilityDescRu',
      title: 'Trust & Reliability Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    // Certifications Section
    defineField({
      name: 'ourCertificationsAr',
      title: 'Certifications Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'ourCertificationsEn',
      title: 'Certifications Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'ourCertificationsRu',
      title: 'Certifications Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'iso9001DescAr',
      title: 'ISO 9001 Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'iso9001DescEn',
      title: 'ISO 9001 Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'iso9001DescRu',
      title: 'ISO 9001 Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalGapDescAr',
      title: 'Global G.A.P Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalGapDescEn',
      title: 'Global G.A.P Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'globalGapDescRu',
      title: 'Global G.A.P Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'haccpDescAr',
      title: 'HACCP Description (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'haccpDescEn',
      title: 'HACCP Description (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'haccpDescRu',
      title: 'HACCP Description (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    // Journey Section
    defineField({
      name: 'ourJourneyAr',
      title: 'Our Journey Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'ourJourneyEn',
      title: 'Our Journey Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'ourJourneyRu',
      title: 'Our Journey Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2009TitleAr',
      title: '2009 Milestone Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2009TitleEn',
      title: '2009 Milestone Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2009TitleRu',
      title: '2009 Milestone Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2009DescAr',
      title: '2009 Milestone Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2009DescEn',
      title: '2009 Milestone Desc (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2009DescRu',
      title: '2009 Milestone Desc (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2012TitleAr',
      title: '2012 Milestone Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2012TitleEn',
      title: '2012 Milestone Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2012TitleRu',
      title: '2012 Milestone Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2012DescAr',
      title: '2012 Milestone Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2012DescEn',
      title: '2012 Milestone Desc (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2012DescRu',
      title: '2012 Milestone Desc (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2015TitleAr',
      title: '2015 Milestone Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2015TitleEn',
      title: '2015 Milestone Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2015TitleRu',
      title: '2015 Milestone Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2015DescAr',
      title: '2015 Milestone Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2015DescEn',
      title: '2015 Milestone Desc (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2015DescRu',
      title: '2015 Milestone Desc (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2018TitleAr',
      title: '2018 Milestone Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2018TitleEn',
      title: '2018 Milestone Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2018TitleRu',
      title: '2018 Milestone Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2018DescAr',
      title: '2018 Milestone Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2018DescEn',
      title: '2018 Milestone Desc (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2018DescRu',
      title: '2018 Milestone Desc (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2021TitleAr',
      title: '2021 Milestone Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2021TitleEn',
      title: '2021 Milestone Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2021TitleRu',
      title: '2021 Milestone Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2021DescAr',
      title: '2021 Milestone Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2021DescEn',
      title: '2021 Milestone Desc (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2021DescRu',
      title: '2021 Milestone Desc (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2025TitleAr',
      title: '2025 Milestone Title (Arabic)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2025TitleEn',
      title: '2025 Milestone Title (English)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2025TitleRu',
      title: '2025 Milestone Title (Russian)',
      type: 'string',
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2025DescAr',
      title: '2025 Milestone Desc (Arabic)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2025DescEn',
      title: '2025 Milestone Desc (English)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),
    defineField({
      name: 'journey2025DescRu',
      title: '2025 Milestone Desc (Russian)',
      type: 'text',
      rows: 2,
      group: 'aboutContent',
      hidden: ({ document }) => document?.pageType !== 'about',
    }),

    // ============================================
    // GENERIC CONTENT (Rich Text)
    // ============================================
    defineField({
      name: 'contentAr',
      title: 'Arabic Content',
      type: 'array',
      group: 'content',
      hidden: true, // Not used on website
      of: [
        defineArrayMember({ type: 'block' }),
        defineArrayMember({ type: 'image' })
      ],
    }),
    defineField({
      name: 'contentEn',
      title: 'English Content',
      type: 'array',
      group: 'content',
      hidden: true, // Not used on website
      of: [
        defineArrayMember({ type: 'block' }),
        defineArrayMember({ type: 'image' })
      ],
    }),

    // ============================================
    // SEO
    // ============================================
    defineField({
      name: 'seo',
      title: 'SEO Settings',
      type: 'object',
      group: 'seo',
      fields: [
        { name: 'metaTitleAr', type: 'string', title: 'Meta Title (Ar)' },
        { name: 'metaTitleEn', type: 'string', title: 'Meta Title (En)' },
        { name: 'metaDescAr', type: 'text', title: 'Meta Description (Ar)', rows: 3 },
        { name: 'metaDescEn', type: 'text', title: 'Meta Description (En)', rows: 3 },
        { name: 'shareImage', type: 'image' },
      ]
    }),
    // Legacy SEO fields (for backward compatibility with existing data)
    defineField({
      name: 'seoAr',
      title: 'SEO (Arabic) - Legacy',
      type: 'object',
      group: 'seo',
      fields: [
        { name: 'metaTitle', type: 'string', title: 'Meta Title' },
        { name: 'metaDescription', type: 'text', title: 'Meta Description', rows: 3 },
      ]
    }),
    defineField({
      name: 'seoEn',
      title: 'SEO (English) - Legacy',
      type: 'object',
      group: 'seo',
      fields: [
        { name: 'metaTitle', type: 'string', title: 'Meta Title' },
        { name: 'metaDescription', type: 'text', title: 'Meta Description', rows: 3 },
      ]
    }),
    defineField({
      name: 'seoRu',
      title: 'SEO (Russian) - Legacy',
      type: 'object',
      group: 'seo',
      fields: [
        { name: 'metaTitle', type: 'string', title: 'Meta Title' },
        { name: 'metaDescription', type: 'text', title: 'Meta Description', rows: 3 },
      ]
    }),

  ],

  preview: {
    select: {
      titleEn: 'titleEn',
      titleAr: 'titleAr',
      pageType: 'pageType',
      isPublished: 'isPublished',
    },
    prepare({ titleEn, titleAr, pageType, isPublished }) {
      const typeIcons: Record<string, string> = {
        'home': '🏠',
        'about': 'ℹ️',
        'contact': '📞',
        'services': '📋',
        'generic': '📄',
      }
      const icon = pageType ? typeIcons[pageType] || '📄' : '📄'
      const status = isPublished ? '✅' : '📝'

      return {
        title: `${icon} ${titleEn || titleAr || 'Untitled'}`,
        subtitle: `${status} ${pageType || 'No Type'} • ${titleAr || ''}`,
      }
    },
  },

  orderings: [
    {
      title: 'Menu Order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
    {
      title: 'Title (A-Z)',
      name: 'titleAsc',
      by: [{ field: 'titleEn', direction: 'asc' }],
    },
  ],
})
