import { defineType, defineField } from 'sanity'

/**
 * Site Settings - Singleton Document
 * Auto-generated by studio/scripts/generate-site-settings-schema.ts
 */
export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: '⚙️ Site Settings',
  type: 'document',
  groups: [
    { name: 'navigation', title: '🧭 Navigation', default: true },
    { name: 'buttons', title: '🔘 Buttons' },
    { name: 'forms', title: '📝 Forms' },
    { name: 'errors', title: '❌ Errors' },
    { name: 'footer', title: '👣 Footer' },
    { name: 'common', title: '🌐 Common' },
  ],
  fields: [
    // NAVIGATION
    defineField({
      name: 'aboutUsAr',
      title: 'About Us (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'aboutUsEn',
      title: 'About Us (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'aboutUsRu',
      title: 'About Us (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'companyNameAr',
      title: 'Company Name (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'companyNameEn',
      title: 'Company Name (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'companyNameRu',
      title: 'Company Name (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'contactAr',
      title: 'Contact (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'contactEn',
      title: 'Contact (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'contactRu',
      title: 'Contact (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'exportingAr',
      title: 'Exporting (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'exportingEn',
      title: 'Exporting (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'exportingRu',
      title: 'Exporting (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'packingAr',
      title: 'Packing (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'packingEn',
      title: 'Packing (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'packingRu',
      title: 'Packing (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'processingAr',
      title: 'Processing (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'processingEn',
      title: 'Processing (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'processingRu',
      title: 'Processing (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'productsAr',
      title: 'Products (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'productsEn',
      title: 'Products (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'productsRu',
      title: 'Products (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'requestQuoteAr',
      title: 'Request Quote (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'requestQuoteEn',
      title: 'Request Quote (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'requestQuoteRu',
      title: 'Request Quote (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'seasonalCalendarAr',
      title: 'Seasonal Calendar (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'seasonalCalendarEn',
      title: 'Seasonal Calendar (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'seasonalCalendarRu',
      title: 'Seasonal Calendar (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    defineField({
      name: 'sortingAr',
      title: 'Sorting (Arabic)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'sortingEn',
      title: 'Sorting (English)',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'sortingRu',
      title: 'Sorting (Russian)',
      type: 'string',
      group: 'navigation',
    }),

    // BUTTONS
    defineField({
      name: 'backButtonAr',
      title: 'Back Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'backButtonEn',
      title: 'Back Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'backButtonRu',
      title: 'Back Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'backToContactOptionsAr',
      title: 'Back To Contact Options (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'backToContactOptionsEn',
      title: 'Back To Contact Options (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'backToContactOptionsRu',
      title: 'Back To Contact Options (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'backToHomeButtonAr',
      title: 'Back To Home Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'backToHomeButtonEn',
      title: 'Back To Home Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'backToHomeButtonRu',
      title: 'Back To Home Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'clearFormButtonAr',
      title: 'Clear Form Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'clearFormButtonEn',
      title: 'Clear Form Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'clearFormButtonRu',
      title: 'Clear Form Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'contactSalesLinkAr',
      title: 'Contact Sales Link (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'contactSalesLinkEn',
      title: 'Contact Sales Link (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'contactSalesLinkRu',
      title: 'Contact Sales Link (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'continueButtonAr',
      title: 'Continue Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'continueButtonEn',
      title: 'Continue Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'continueButtonRu',
      title: 'Continue Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'nextButtonAr',
      title: 'Next Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'nextButtonEn',
      title: 'Next Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'nextButtonRu',
      title: 'Next Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'refreshButtonAr',
      title: 'Refresh Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'refreshButtonEn',
      title: 'Refresh Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'refreshButtonRu',
      title: 'Refresh Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'retryButtonAr',
      title: 'Retry Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'retryButtonEn',
      title: 'Retry Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'retryButtonRu',
      title: 'Retry Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'sendMessageAr',
      title: 'Send Message (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'sendMessageEn',
      title: 'Send Message (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'sendMessageRu',
      title: 'Send Message (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'startFreshButtonAr',
      title: 'Start Fresh Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'startFreshButtonEn',
      title: 'Start Fresh Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'startFreshButtonRu',
      title: 'Start Fresh Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'startQuoteRequestAr',
      title: 'Start Quote Request (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'startQuoteRequestEn',
      title: 'Start Quote Request (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'startQuoteRequestRu',
      title: 'Start Quote Request (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'submitAnotherButtonAr',
      title: 'Submit Another Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'submitAnotherButtonEn',
      title: 'Submit Another Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'submitAnotherButtonRu',
      title: 'Submit Another Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'submitButtonAr',
      title: 'Submit Button (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'submitButtonEn',
      title: 'Submit Button (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'submitButtonRu',
      title: 'Submit Button (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'viewAllProductsAr',
      title: 'View All Products (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewAllProductsEn',
      title: 'View All Products (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewAllProductsRu',
      title: 'View All Products (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'viewByMonthAr',
      title: 'View By Month (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewByMonthEn',
      title: 'View By Month (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewByMonthRu',
      title: 'View By Month (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'viewCalendarAr',
      title: 'View Calendar (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewCalendarEn',
      title: 'View Calendar (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewCalendarRu',
      title: 'View Calendar (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'viewFullCalendarAr',
      title: 'View Full Calendar (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewFullCalendarEn',
      title: 'View Full Calendar (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewFullCalendarRu',
      title: 'View Full Calendar (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'viewOnGoogleMapsAr',
      title: 'View On Google Maps (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewOnGoogleMapsEn',
      title: 'View On Google Maps (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewOnGoogleMapsRu',
      title: 'View On Google Maps (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    defineField({
      name: 'viewProductsAr',
      title: 'View Products (Arabic)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewProductsEn',
      title: 'View Products (English)',
      type: 'string',
      group: 'buttons',
    }),
    defineField({
      name: 'viewProductsRu',
      title: 'View Products (Russian)',
      type: 'string',
      group: 'buttons',
    }),

    // FORMS
    defineField({
      name: 'additionalMessageLabelAr',
      title: 'Additional Message Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'additionalMessageLabelEn',
      title: 'Additional Message Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'additionalMessageLabelRu',
      title: 'Additional Message Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'companyAr',
      title: 'Company (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'companyEn',
      title: 'Company (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'companyRu',
      title: 'Company (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'companyNameLabelAr',
      title: 'Company Name Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'companyNameLabelEn',
      title: 'Company Name Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'companyNameLabelRu',
      title: 'Company Name Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'contactPersonLabelAr',
      title: 'Contact Person Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'contactPersonLabelEn',
      title: 'Contact Person Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'contactPersonLabelRu',
      title: 'Contact Person Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'countryAr',
      title: 'Country (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'countryEn',
      title: 'Country (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'countryRu',
      title: 'Country (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'deliveryTimeframeLabelAr',
      title: 'Delivery Timeframe Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'deliveryTimeframeLabelEn',
      title: 'Delivery Timeframe Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'deliveryTimeframeLabelRu',
      title: 'Delivery Timeframe Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'deliveryTimeframePlaceholderAr',
      title: 'Delivery Timeframe Placeholder (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'deliveryTimeframePlaceholderEn',
      title: 'Delivery Timeframe Placeholder (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'deliveryTimeframePlaceholderRu',
      title: 'Delivery Timeframe Placeholder (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'emailAr',
      title: 'Email (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'emailEn',
      title: 'Email (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'emailRu',
      title: 'Email (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'emailAddressLabelAr',
      title: 'Email Address Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'emailAddressLabelEn',
      title: 'Email Address Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'emailAddressLabelRu',
      title: 'Email Address Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'estimatedQuantityLabelAr',
      title: 'Estimated Quantity Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'estimatedQuantityLabelEn',
      title: 'Estimated Quantity Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'estimatedQuantityLabelRu',
      title: 'Estimated Quantity Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'fullNameAr',
      title: 'Full Name (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'fullNameEn',
      title: 'Full Name (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'fullNameRu',
      title: 'Full Name (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'messageAr',
      title: 'Message (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'messageEn',
      title: 'Message (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'messageRu',
      title: 'Message (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'optionalTextAr',
      title: 'Optional Text (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'optionalTextEn',
      title: 'Optional Text (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'optionalTextRu',
      title: 'Optional Text (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'phoneAr',
      title: 'Phone (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'phoneEn',
      title: 'Phone (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'phoneRu',
      title: 'Phone (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'phoneNumberLabelAr',
      title: 'Phone Number Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'phoneNumberLabelEn',
      title: 'Phone Number Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'phoneNumberLabelRu',
      title: 'Phone Number Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'selectCountryPlaceholderAr',
      title: 'Select Country Placeholder (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'selectCountryPlaceholderEn',
      title: 'Select Country Placeholder (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'selectCountryPlaceholderRu',
      title: 'Select Country Placeholder (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'selectProductsLabelAr',
      title: 'Select Products Label (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'selectProductsLabelEn',
      title: 'Select Products Label (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'selectProductsLabelRu',
      title: 'Select Products Label (Russian)',
      type: 'string',
      group: 'forms',
    }),

    defineField({
      name: 'selectQuantityPlaceholderAr',
      title: 'Select Quantity Placeholder (Arabic)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'selectQuantityPlaceholderEn',
      title: 'Select Quantity Placeholder (English)',
      type: 'string',
      group: 'forms',
    }),
    defineField({
      name: 'selectQuantityPlaceholderRu',
      title: 'Select Quantity Placeholder (Russian)',
      type: 'string',
      group: 'forms',
    }),

    // ERRORS
    defineField({
      name: 'errorAr',
      title: 'Error (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorEn',
      title: 'Error (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorRu',
      title: 'Error (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorCheckConnectionAr',
      title: 'Error Check Connection (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorCheckConnectionEn',
      title: 'Error Check Connection (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorCheckConnectionRu',
      title: 'Error Check Connection (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorContactSupportAr',
      title: 'Error Contact Support (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorContactSupportEn',
      title: 'Error Contact Support (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorContactSupportRu',
      title: 'Error Contact Support (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorLoadingImageAr',
      title: 'Error Loading Image (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorLoadingImageEn',
      title: 'Error Loading Image (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorLoadingImageRu',
      title: 'Error Loading Image (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorPreparingDataAr',
      title: 'Error Preparing Data (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorPreparingDataEn',
      title: 'Error Preparing Data (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorPreparingDataRu',
      title: 'Error Preparing Data (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorPreparingDataMessageAr',
      title: 'Error Preparing Data Message (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorPreparingDataMessageEn',
      title: 'Error Preparing Data Message (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorPreparingDataMessageRu',
      title: 'Error Preparing Data Message (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorTitleAr',
      title: 'Error Title (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorTitleEn',
      title: 'Error Title (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorTitleRu',
      title: 'Error Title (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorTryAgainAr',
      title: 'Error Try Again (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorTryAgainEn',
      title: 'Error Try Again (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorTryAgainRu',
      title: 'Error Try Again (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorVerifyFieldsAr',
      title: 'Error Verify Fields (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorVerifyFieldsEn',
      title: 'Error Verify Fields (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorVerifyFieldsRu',
      title: 'Error Verify Fields (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'errorWhatToDoAr',
      title: 'Error What To Do (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorWhatToDoEn',
      title: 'Error What To Do (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'errorWhatToDoRu',
      title: 'Error What To Do (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'loadingCalendarAr',
      title: 'Loading Calendar (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'loadingCalendarEn',
      title: 'Loading Calendar (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'loadingCalendarRu',
      title: 'Loading Calendar (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'loadingProductsTextAr',
      title: 'Loading Products Text (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'loadingProductsTextEn',
      title: 'Loading Products Text (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'loadingProductsTextRu',
      title: 'Loading Products Text (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'noProductsMessageAr',
      title: 'No Products Message (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'noProductsMessageEn',
      title: 'No Products Message (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'noProductsMessageRu',
      title: 'No Products Message (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'noProductsTitleAr',
      title: 'No Products Title (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'noProductsTitleEn',
      title: 'No Products Title (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'noProductsTitleRu',
      title: 'No Products Title (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'offlineAr',
      title: 'Offline (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'offlineEn',
      title: 'Offline (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'offlineRu',
      title: 'Offline (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'offlineMessageAr',
      title: 'Offline Message (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'offlineMessageEn',
      title: 'Offline Message (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'offlineMessageRu',
      title: 'Offline Message (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'onlineAr',
      title: 'Online (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'onlineEn',
      title: 'Online (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'onlineRu',
      title: 'Online (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'unableToLoadProductsMessageAr',
      title: 'Unable To Load Products Message (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'unableToLoadProductsMessageEn',
      title: 'Unable To Load Products Message (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'unableToLoadProductsMessageRu',
      title: 'Unable To Load Products Message (Russian)',
      type: 'string',
      group: 'errors',
    }),

    defineField({
      name: 'unableToLoadProductsTitleAr',
      title: 'Unable To Load Products Title (Arabic)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'unableToLoadProductsTitleEn',
      title: 'Unable To Load Products Title (English)',
      type: 'string',
      group: 'errors',
    }),
    defineField({
      name: 'unableToLoadProductsTitleRu',
      title: 'Unable To Load Products Title (Russian)',
      type: 'string',
      group: 'errors',
    }),

    // FOOTER
    defineField({
      name: 'cairoEgyptAr',
      title: 'Cairo Egypt (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'cairoEgyptEn',
      title: 'Cairo Egypt (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'cairoEgyptRu',
      title: 'Cairo Egypt (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'companyLocationTitleAr',
      title: 'Company Location Title (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'companyLocationTitleEn',
      title: 'Company Location Title (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'companyLocationTitleRu',
      title: 'Company Location Title (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'copyrightAr',
      title: 'Copyright (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'copyrightEn',
      title: 'Copyright (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'copyrightRu',
      title: 'Copyright (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'footerCopyrightAr',
      title: 'Footer Copyright (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerCopyrightEn',
      title: 'Footer Copyright (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerCopyrightRu',
      title: 'Footer Copyright (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'footerDescriptionAr',
      title: 'Footer Description (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerDescriptionEn',
      title: 'Footer Description (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerDescriptionRu',
      title: 'Footer Description (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'footerPrivacyPolicyAr',
      title: 'Footer Privacy Policy (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerPrivacyPolicyEn',
      title: 'Footer Privacy Policy (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerPrivacyPolicyRu',
      title: 'Footer Privacy Policy (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'footerTermsOfServiceAr',
      title: 'Footer Terms Of Service (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerTermsOfServiceEn',
      title: 'Footer Terms Of Service (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerTermsOfServiceRu',
      title: 'Footer Terms Of Service (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'ourLocationAr',
      title: 'Our Location (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'ourLocationEn',
      title: 'Our Location (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'ourLocationRu',
      title: 'Our Location (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'privacyPolicyAr',
      title: 'Privacy Policy (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'privacyPolicyEn',
      title: 'Privacy Policy (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'privacyPolicyRu',
      title: 'Privacy Policy (Russian)',
      type: 'string',
      group: 'footer',
    }),

    defineField({
      name: 'termsOfServiceAr',
      title: 'Terms Of Service (Arabic)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'termsOfServiceEn',
      title: 'Terms Of Service (English)',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'termsOfServiceRu',
      title: 'Terms Of Service (Russian)',
      type: 'string',
      group: 'footer',
    }),

    // COMMON
    defineField({
      name: 'aprilAr',
      title: 'April (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'aprilEn',
      title: 'April (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'aprilRu',
      title: 'April (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'augustAr',
      title: 'August (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'augustEn',
      title: 'August (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'augustRu',
      title: 'August (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'authErrorAr',
      title: 'Auth Error (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'authErrorEn',
      title: 'Auth Error (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'authErrorRu',
      title: 'Auth Error (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'backToProductsAr',
      title: 'Back To Products (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'backToProductsEn',
      title: 'Back To Products (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'backToProductsRu',
      title: 'Back To Products (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'berriesAr',
      title: 'Berries (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'berriesEn',
      title: 'Berries (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'berriesRu',
      title: 'Berries (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'calendarAvailableAr',
      title: 'Calendar Available (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarAvailableEn',
      title: 'Calendar Available (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarAvailableRu',
      title: 'Calendar Available (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'calendarNotAvailableAr',
      title: 'Calendar Not Available (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarNotAvailableEn',
      title: 'Calendar Not Available (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarNotAvailableRu',
      title: 'Calendar Not Available (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'calendarSeasonalAvailabilityAr',
      title: 'Calendar Seasonal Availability (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarSeasonalAvailabilityEn',
      title: 'Calendar Seasonal Availability (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarSeasonalAvailabilityRu',
      title: 'Calendar Seasonal Availability (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'calendarViewFullCalendarAr',
      title: 'Calendar View Full Calendar (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarViewFullCalendarEn',
      title: 'Calendar View Full Calendar (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'calendarViewFullCalendarRu',
      title: 'Calendar View Full Calendar (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'categoryBerriesAr',
      title: 'Category Berries (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryBerriesEn',
      title: 'Category Berries (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryBerriesRu',
      title: 'Category Berries (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'categoryCitrusAr',
      title: 'Category Citrus (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryCitrusEn',
      title: 'Category Citrus (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryCitrusRu',
      title: 'Category Citrus (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'categoryGrapesAr',
      title: 'Category Grapes (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryGrapesEn',
      title: 'Category Grapes (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryGrapesRu',
      title: 'Category Grapes (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'categoryLemonsAr',
      title: 'Category Lemons (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryLemonsEn',
      title: 'Category Lemons (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryLemonsRu',
      title: 'Category Lemons (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'categoryVegetablesAr',
      title: 'Category Vegetables (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryVegetablesEn',
      title: 'Category Vegetables (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'categoryVegetablesRu',
      title: 'Category Vegetables (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'citrusAr',
      title: 'Citrus (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'citrusEn',
      title: 'Citrus (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'citrusRu',
      title: 'Citrus (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'clearCacheAr',
      title: 'Clear Cache (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'clearCacheEn',
      title: 'Clear Cache (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'clearCacheRu',
      title: 'Clear Cache (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'coldStorageAr',
      title: 'Cold Storage (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'coldStorageEn',
      title: 'Cold Storage (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'coldStorageRu',
      title: 'Cold Storage (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'commonCompanyNameAr',
      title: 'Common Company Name (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonCompanyNameEn',
      title: 'Common Company Name (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonCompanyNameRu',
      title: 'Common Company Name (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'commonErrorAr',
      title: 'Common Error (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonErrorEn',
      title: 'Common Error (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonErrorRu',
      title: 'Common Error (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'commonHomeAr',
      title: 'Common Home (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonHomeEn',
      title: 'Common Home (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonHomeRu',
      title: 'Common Home (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'commonLoadingAr',
      title: 'Common Loading (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonLoadingEn',
      title: 'Common Loading (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonLoadingRu',
      title: 'Common Loading (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'commonRetryAr',
      title: 'Common Retry (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonRetryEn',
      title: 'Common Retry (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonRetryRu',
      title: 'Common Retry (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'commonViewDetailsAr',
      title: 'Common View Details (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonViewDetailsEn',
      title: 'Common View Details (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'commonViewDetailsRu',
      title: 'Common View Details (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'connectionErrorAr',
      title: 'Connection Error (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'connectionErrorEn',
      title: 'Connection Error (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'connectionErrorRu',
      title: 'Connection Error (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'ctaGetYourQuoteTodayAr',
      title: 'Cta Get Your Quote Today (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ctaGetYourQuoteTodayEn',
      title: 'Cta Get Your Quote Today (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ctaGetYourQuoteTodayRu',
      title: 'Cta Get Your Quote Today (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'ctaReadyToImportAr',
      title: 'Cta Ready To Import (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ctaReadyToImportEn',
      title: 'Cta Ready To Import (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ctaReadyToImportRu',
      title: 'Cta Ready To Import (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'customerSatisfactionAr',
      title: 'Customer Satisfaction (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'customerSatisfactionEn',
      title: 'Customer Satisfaction (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'customerSatisfactionRu',
      title: 'Customer Satisfaction (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'decemberAr',
      title: 'December (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'decemberEn',
      title: 'December (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'decemberRu',
      title: 'December (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'februaryAr',
      title: 'February (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'februaryEn',
      title: 'February (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'februaryRu',
      title: 'February (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'fillAllFieldsAr',
      title: 'Fill All Fields (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'fillAllFieldsEn',
      title: 'Fill All Fields (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'fillAllFieldsRu',
      title: 'Fill All Fields (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formBackAr',
      title: 'Form Back (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formBackEn',
      title: 'Form Back (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formBackRu',
      title: 'Form Back (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formCompanyAr',
      title: 'Form Company (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formCompanyEn',
      title: 'Form Company (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formCompanyRu',
      title: 'Form Company (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formCountryAr',
      title: 'Form Country (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formCountryEn',
      title: 'Form Country (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formCountryRu',
      title: 'Form Country (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formEmailAr',
      title: 'Form Email (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formEmailEn',
      title: 'Form Email (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formEmailRu',
      title: 'Form Email (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formFullNameAr',
      title: 'Form Full Name (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formFullNameEn',
      title: 'Form Full Name (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formFullNameRu',
      title: 'Form Full Name (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formMessageAr',
      title: 'Form Message (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formMessageEn',
      title: 'Form Message (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formMessageRu',
      title: 'Form Message (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formNextAr',
      title: 'Form Next (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formNextEn',
      title: 'Form Next (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formNextRu',
      title: 'Form Next (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formPhoneAr',
      title: 'Form Phone (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formPhoneEn',
      title: 'Form Phone (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formPhoneRu',
      title: 'Form Phone (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formSendMessageAr',
      title: 'Form Send Message (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formSendMessageEn',
      title: 'Form Send Message (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formSendMessageRu',
      title: 'Form Send Message (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'formSubmitAr',
      title: 'Form Submit (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formSubmitEn',
      title: 'Form Submit (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'formSubmitRu',
      title: 'Form Submit (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'globalGapDescAr',
      title: 'Global Gap Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'globalGapDescEn',
      title: 'Global Gap Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'globalGapDescRu',
      title: 'Global Gap Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'globalReachAr',
      title: 'Global Reach (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'globalReachEn',
      title: 'Global Reach (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'globalReachRu',
      title: 'Global Reach (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'globalReachDescAr',
      title: 'Global Reach Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'globalReachDescEn',
      title: 'Global Reach Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'globalReachDescRu',
      title: 'Global Reach Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'grapesAr',
      title: 'Grapes (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'grapesEn',
      title: 'Grapes (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'grapesRu',
      title: 'Grapes (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'haccpDescAr',
      title: 'Haccp Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'haccpDescEn',
      title: 'Haccp Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'haccpDescRu',
      title: 'Haccp Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'heroViewProductsAr',
      title: 'Hero View Products (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'heroViewProductsEn',
      title: 'Hero View Products (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'heroViewProductsRu',
      title: 'Hero View Products (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'homeAr',
      title: 'Home (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'homeEn',
      title: 'Home (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'homeRu',
      title: 'Home (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'innovationAr',
      title: 'Innovation (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'innovationEn',
      title: 'Innovation (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'innovationRu',
      title: 'Innovation (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'innovationDescAr',
      title: 'Innovation Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'innovationDescEn',
      title: 'Innovation Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'innovationDescRu',
      title: 'Innovation Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'invalidProductDataAr',
      title: 'Invalid Product Data (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'invalidProductDataEn',
      title: 'Invalid Product Data (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'invalidProductDataRu',
      title: 'Invalid Product Data (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'invalidProductDataMessageAr',
      title: 'Invalid Product Data Message (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'invalidProductDataMessageEn',
      title: 'Invalid Product Data Message (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'invalidProductDataMessageRu',
      title: 'Invalid Product Data Message (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'iso9001DescAr',
      title: 'Iso9001 Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'iso9001DescEn',
      title: 'Iso9001 Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'iso9001DescRu',
      title: 'Iso9001 Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'januaryAr',
      title: 'January (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'januaryEn',
      title: 'January (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'januaryRu',
      title: 'January (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'julyAr',
      title: 'July (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'julyEn',
      title: 'July (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'julyRu',
      title: 'July (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'juneAr',
      title: 'June (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'juneEn',
      title: 'June (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'juneRu',
      title: 'June (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'lemonsAr',
      title: 'Lemons (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'lemonsEn',
      title: 'Lemons (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'lemonsRu',
      title: 'Lemons (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'loadFailedAr',
      title: 'Load Failed (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'loadFailedEn',
      title: 'Load Failed (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'loadFailedRu',
      title: 'Load Failed (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'loadingAr',
      title: 'Loading (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'loadingEn',
      title: 'Loading (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'loadingRu',
      title: 'Loading (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'loadingProductAr',
      title: 'Loading Product (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'loadingProductEn',
      title: 'Loading Product (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'loadingProductRu',
      title: 'Loading Product (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'marchAr',
      title: 'March (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'marchEn',
      title: 'March (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'marchRu',
      title: 'March (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'maxRetriesErrorAr',
      title: 'Max Retries Error (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'maxRetriesErrorEn',
      title: 'Max Retries Error (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'maxRetriesErrorRu',
      title: 'Max Retries Error (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'mayAr',
      title: 'May (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'mayEn',
      title: 'May (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'mayRu',
      title: 'May (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthAprilAr',
      title: 'Month April (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthAprilEn',
      title: 'Month April (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthAprilRu',
      title: 'Month April (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthAugustAr',
      title: 'Month August (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthAugustEn',
      title: 'Month August (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthAugustRu',
      title: 'Month August (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthDecemberAr',
      title: 'Month December (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthDecemberEn',
      title: 'Month December (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthDecemberRu',
      title: 'Month December (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthFebruaryAr',
      title: 'Month February (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthFebruaryEn',
      title: 'Month February (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthFebruaryRu',
      title: 'Month February (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthJanuaryAr',
      title: 'Month January (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthJanuaryEn',
      title: 'Month January (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthJanuaryRu',
      title: 'Month January (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthJulyAr',
      title: 'Month July (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthJulyEn',
      title: 'Month July (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthJulyRu',
      title: 'Month July (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthJuneAr',
      title: 'Month June (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthJuneEn',
      title: 'Month June (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthJuneRu',
      title: 'Month June (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthMarchAr',
      title: 'Month March (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthMarchEn',
      title: 'Month March (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthMarchRu',
      title: 'Month March (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthMayAr',
      title: 'Month May (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthMayEn',
      title: 'Month May (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthMayRu',
      title: 'Month May (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthNovemberAr',
      title: 'Month November (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthNovemberEn',
      title: 'Month November (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthNovemberRu',
      title: 'Month November (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthOctoberAr',
      title: 'Month October (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthOctoberEn',
      title: 'Month October (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthOctoberRu',
      title: 'Month October (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'monthSeptemberAr',
      title: 'Month September (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthSeptemberEn',
      title: 'Month September (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'monthSeptemberRu',
      title: 'Month September (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navAboutUsAr',
      title: 'Nav About Us (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navAboutUsEn',
      title: 'Nav About Us (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navAboutUsRu',
      title: 'Nav About Us (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navContactAr',
      title: 'Nav Contact (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navContactEn',
      title: 'Nav Contact (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navContactRu',
      title: 'Nav Contact (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navExportingAr',
      title: 'Nav Exporting (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navExportingEn',
      title: 'Nav Exporting (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navExportingRu',
      title: 'Nav Exporting (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navPackingAr',
      title: 'Nav Packing (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navPackingEn',
      title: 'Nav Packing (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navPackingRu',
      title: 'Nav Packing (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navProcessingAr',
      title: 'Nav Processing (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navProcessingEn',
      title: 'Nav Processing (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navProcessingRu',
      title: 'Nav Processing (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navProductsAr',
      title: 'Nav Products (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navProductsEn',
      title: 'Nav Products (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navProductsRu',
      title: 'Nav Products (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navRequestQuoteAr',
      title: 'Nav Request Quote (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navRequestQuoteEn',
      title: 'Nav Request Quote (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navRequestQuoteRu',
      title: 'Nav Request Quote (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navSeasonalCalendarAr',
      title: 'Nav Seasonal Calendar (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navSeasonalCalendarEn',
      title: 'Nav Seasonal Calendar (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navSeasonalCalendarRu',
      title: 'Nav Seasonal Calendar (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'navSortingAr',
      title: 'Nav Sorting (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navSortingEn',
      title: 'Nav Sorting (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'navSortingRu',
      title: 'Nav Sorting (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'networkErrorAr',
      title: 'Network Error (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'networkErrorEn',
      title: 'Network Error (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'networkErrorRu',
      title: 'Network Error (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'noProductsFoundAr',
      title: 'No Products Found (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'noProductsFoundEn',
      title: 'No Products Found (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'noProductsFoundRu',
      title: 'No Products Found (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'novemberAr',
      title: 'November (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'novemberEn',
      title: 'November (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'novemberRu',
      title: 'November (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'octoberAr',
      title: 'October (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'octoberEn',
      title: 'October (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'octoberRu',
      title: 'October (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'orangesAr',
      title: 'Oranges (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'orangesEn',
      title: 'Oranges (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'orangesRu',
      title: 'Oranges (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'otherCountryAr',
      title: 'Other Country (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'otherCountryEn',
      title: 'Other Country (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'otherCountryRu',
      title: 'Other Country (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'ourCertificationsAr',
      title: 'Our Certifications (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ourCertificationsEn',
      title: 'Our Certifications (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ourCertificationsRu',
      title: 'Our Certifications (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'ourJourneyAr',
      title: 'Our Journey (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ourJourneyEn',
      title: 'Our Journey (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'ourJourneyRu',
      title: 'Our Journey (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'partnershipAr',
      title: 'Partnership (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'partnershipEn',
      title: 'Partnership (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'partnershipRu',
      title: 'Partnership (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'partnershipDescAr',
      title: 'Partnership Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'partnershipDescEn',
      title: 'Partnership Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'partnershipDescRu',
      title: 'Partnership Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'pomegranatesAr',
      title: 'Pomegranates (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'pomegranatesEn',
      title: 'Pomegranates (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'pomegranatesRu',
      title: 'Pomegranates (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsPackagingAr',
      title: 'Products Packaging (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsPackagingEn',
      title: 'Products Packaging (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsPackagingRu',
      title: 'Products Packaging (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsShelfLifeAr',
      title: 'Products Shelf Life (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsShelfLifeEn',
      title: 'Products Shelf Life (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsShelfLifeRu',
      title: 'Products Shelf Life (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsSizesAr',
      title: 'Products Sizes (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsSizesEn',
      title: 'Products Sizes (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsSizesRu',
      title: 'Products Sizes (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsSpecificationsAr',
      title: 'Products Specifications (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsSpecificationsEn',
      title: 'Products Specifications (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsSpecificationsRu',
      title: 'Products Specifications (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsStorageAr',
      title: 'Products Storage (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsStorageEn',
      title: 'Products Storage (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsStorageRu',
      title: 'Products Storage (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsFreshCertifiedDeliveredAr',
      title: 'Products Fresh Certified Delivered (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsFreshCertifiedDeliveredEn',
      title: 'Products Fresh Certified Delivered (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsFreshCertifiedDeliveredRu',
      title: 'Products Fresh Certified Delivered (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsOurPremiumProductsAr',
      title: 'Products Our Premium Products (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsOurPremiumProductsEn',
      title: 'Products Our Premium Products (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsOurPremiumProductsRu',
      title: 'Products Our Premium Products (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'productsViewAllProductsAr',
      title: 'Products View All Products (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsViewAllProductsEn',
      title: 'Products View All Products (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'productsViewAllProductsRu',
      title: 'Products View All Products (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'qualityFirstAr',
      title: 'Quality First (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'qualityFirstEn',
      title: 'Quality First (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'qualityFirstRu',
      title: 'Quality First (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'qualityFirstDescAr',
      title: 'Quality First Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'qualityFirstDescEn',
      title: 'Quality First Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'qualityFirstDescRu',
      title: 'Quality First Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'refreshPageAr',
      title: 'Refresh Page (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'refreshPageEn',
      title: 'Refresh Page (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'refreshPageRu',
      title: 'Refresh Page (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'requestQuoteSubtitleAr',
      title: 'Request Quote Subtitle (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'requestQuoteSubtitleEn',
      title: 'Request Quote Subtitle (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'requestQuoteSubtitleRu',
      title: 'Request Quote Subtitle (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'requestQuoteTitleAr',
      title: 'Request Quote Title (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'requestQuoteTitleEn',
      title: 'Request Quote Title (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'requestQuoteTitleRu',
      title: 'Request Quote Title (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'retryAr',
      title: 'Retry (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'retryEn',
      title: 'Retry (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'retryRu',
      title: 'Retry (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'scheduleCallbackAr',
      title: 'Schedule Callback (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'scheduleCallbackEn',
      title: 'Schedule Callback (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'scheduleCallbackRu',
      title: 'Schedule Callback (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'septemberAr',
      title: 'September (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'septemberEn',
      title: 'September (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'septemberRu',
      title: 'September (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'serverErrorAr',
      title: 'Server Error (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'serverErrorEn',
      title: 'Server Error (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'serverErrorRu',
      title: 'Server Error (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'shareRequirementsAr',
      title: 'Share Requirements (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'shareRequirementsEn',
      title: 'Share Requirements (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'shareRequirementsRu',
      title: 'Share Requirements (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'shippingAr',
      title: 'Shipping (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'shippingEn',
      title: 'Shipping (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'shippingRu',
      title: 'Shipping (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'showingCachedAr',
      title: 'Showing Cached (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'showingCachedEn',
      title: 'Showing Cached (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'showingCachedRu',
      title: 'Showing Cached (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'storageRequirementsDescAr',
      title: 'Storage Requirements Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'storageRequirementsDescEn',
      title: 'Storage Requirements Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'storageRequirementsDescRu',
      title: 'Storage Requirements Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'strawberriesAr',
      title: 'Strawberries (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'strawberriesEn',
      title: 'Strawberries (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'strawberriesRu',
      title: 'Strawberries (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'submitQuoteRequestAr',
      title: 'Submit Quote Request (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'submitQuoteRequestEn',
      title: 'Submit Quote Request (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'submitQuoteRequestRu',
      title: 'Submit Quote Request (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'submittingAr',
      title: 'Submitting (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'submittingEn',
      title: 'Submitting (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'submittingRu',
      title: 'Submitting (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'summaryTitleAr',
      title: 'Summary Title (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'summaryTitleEn',
      title: 'Summary Title (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'summaryTitleRu',
      title: 'Summary Title (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'sustainabilityAr',
      title: 'Sustainability (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'sustainabilityEn',
      title: 'Sustainability (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'sustainabilityRu',
      title: 'Sustainability (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'sustainabilityDescAr',
      title: 'Sustainability Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'sustainabilityDescEn',
      title: 'Sustainability Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'sustainabilityDescRu',
      title: 'Sustainability Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'trustAndReliabilityAr',
      title: 'Trust And Reliability (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustAndReliabilityEn',
      title: 'Trust And Reliability (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustAndReliabilityRu',
      title: 'Trust And Reliability (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'trustAndReliabilityDescAr',
      title: 'Trust And Reliability Desc (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustAndReliabilityDescEn',
      title: 'Trust And Reliability Desc (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustAndReliabilityDescRu',
      title: 'Trust And Reliability Desc (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'trustCertifiedAr',
      title: 'Trust Certified (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustCertifiedEn',
      title: 'Trust Certified (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustCertifiedRu',
      title: 'Trust Certified (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'trustContainersPerYearAr',
      title: 'Trust Containers Per Year (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustContainersPerYearEn',
      title: 'Trust Containers Per Year (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustContainersPerYearRu',
      title: 'Trust Containers Per Year (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'trustCountriesServedAr',
      title: 'Trust Countries Served (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustCountriesServedEn',
      title: 'Trust Countries Served (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustCountriesServedRu',
      title: 'Trust Countries Served (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'trustYearsExportingAr',
      title: 'Trust Years Exporting (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustYearsExportingEn',
      title: 'Trust Years Exporting (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'trustYearsExportingRu',
      title: 'Trust Years Exporting (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'tryLaterAr',
      title: 'Try Later (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'tryLaterEn',
      title: 'Try Later (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'tryLaterRu',
      title: 'Try Later (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationCompanyAr',
      title: 'Validation Company (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationCompanyEn',
      title: 'Validation Company (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationCompanyRu',
      title: 'Validation Company (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationContactAr',
      title: 'Validation Contact (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationContactEn',
      title: 'Validation Contact (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationContactRu',
      title: 'Validation Contact (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationCountryAr',
      title: 'Validation Country (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationCountryEn',
      title: 'Validation Country (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationCountryRu',
      title: 'Validation Country (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationDeliveryAr',
      title: 'Validation Delivery (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationDeliveryEn',
      title: 'Validation Delivery (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationDeliveryRu',
      title: 'Validation Delivery (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationEmailAr',
      title: 'Validation Email (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationEmailEn',
      title: 'Validation Email (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationEmailRu',
      title: 'Validation Email (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationPhoneAr',
      title: 'Validation Phone (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationPhoneEn',
      title: 'Validation Phone (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationPhoneRu',
      title: 'Validation Phone (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationQuantityAr',
      title: 'Validation Quantity (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationQuantityEn',
      title: 'Validation Quantity (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationQuantityRu',
      title: 'Validation Quantity (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'validationRequiredAr',
      title: 'Validation Required (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationRequiredEn',
      title: 'Validation Required (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'validationRequiredRu',
      title: 'Validation Required (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'variousOptionsAr',
      title: 'Various Options (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'variousOptionsEn',
      title: 'Various Options (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'variousOptionsRu',
      title: 'Various Options (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'vegetablesAr',
      title: 'Vegetables (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'vegetablesEn',
      title: 'Vegetables (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'vegetablesRu',
      title: 'Vegetables (Russian)',
      type: 'string',
      group: 'common',
    }),

    defineField({
      name: 'viewDetailsAr',
      title: 'View Details (Arabic)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'viewDetailsEn',
      title: 'View Details (English)',
      type: 'string',
      group: 'common',
    }),
    defineField({
      name: 'viewDetailsRu',
      title: 'View Details (Russian)',
      type: 'string',
      group: 'common',
    }),

  ],
  preview: {
    prepare() {
      return {
        title: '⚙️ Site Settings',
        subtitle: 'Global content & settings',
      }
    },
  },
})
